apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: networkingstack
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XNetworkingStack
  mode: Pipeline
  pipeline:
  - step: render-templates
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          {{ $xr := .observed.composite.resource }}
          {{ $region := $xr.spec.region }}
          {{ $vpcId := dig "resources" "vpc" "resource" "status" "atProvider" "id" "" $.observed }}
          ---
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: VPC
          metadata:
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: vpc
          spec:
            forProvider:
              region: {{ $region }}
              cidrBlock: 192.168.0.0/16
              enableDnsHostnames: false
              enableDnsSupport: true
          ---
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: Subnet
          metadata:
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: subnetAZA
          spec:
            forProvider:
              region: {{ $region }}
              availabilityZone: {{ print $region "a" }}
              cidrBlock: 192.168.0.0/18
              {{- if $vpcId }}
              vpcId: {{ $vpcId }}
              {{- end }}
          ---
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: Subnet
          metadata:
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: subnetAZB
          spec:
            forProvider:
              region: {{ $region }}
              availabilityZone: {{ print $region "b" }}
              cidrBlock: 192.168.64.0/18
              {{- if $vpcId }}
              vpcId: {{ $vpcId }}
              {{- end }}
          ---
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: Subnet
          metadata:
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: subnetAZC
          spec:
            forProvider:
              region: {{ $region }}
              availabilityZone: {{ print $region "c" }}
              cidrBlock: 192.168.128.0/18
              {{- if $vpcId }}
              vpcId: {{ $vpcId }}
              {{- end }}
          ---
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: SecurityGroup
          metadata:
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: securityGroup
          spec:
            forProvider:
              name: my-sg-{{ $xr.metadata.name }}
              region: {{ $region }}
              description: something something
              {{- if $vpcId }}
              vpcId: {{ $vpcId }}
              {{- end }}
          ---
          apiVersion: {{ $xr.apiVersion }}
          kind: {{ $xr.kind }}
          status:
            networkingInfo:
              vpcID: "{{ $vpcId }}"
              subnetAZA: "{{ dig "resources" "subnetAZA" "resource" "status" "atProvider" "id" "" $.observed }}"
              subnetAZB: "{{ dig "resources" "subnetAZB" "resource" "status" "atProvider" "id" "" $.observed }}"
              subnetAZC: "{{ dig "resources" "subnetAZC" "resource" "status" "atProvider" "id" "" $.observed }}"
              securityGroup: "{{ dig "resources" "securityGroup" "resource" "status" "atProvider" "id" "" $.observed }}"
  - step: auto-ready
    functionRef:
      name: function-auto-ready
